"""Room

Revision ID: 439986f7ad6e
Revises: 4365e1ad4a42
Create Date: 2017-04-14 14:22:55.730207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439986f7ad6e'
down_revision = '4365e1ad4a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('deathroom', sa.Boolean(), nullable=True),
    sa.Column('nobr', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
